# Generated by Django 6.0.1 on 2026-01-21 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_auction_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('auction_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.auctionevent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL)),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='auctions_au_start_d_08e180_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionevent',
            index=models.Index(fields=['is_active'], name='auctions_au_is_acti_d730af_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['auction_event'], name='auctions_au_auction_8b2507_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['status'], name='auctions_au_status_f2c74a_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['owner'], name='auctions_au_owner_i_efb9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['current_price'], name='auctions_au_current_54aa79_idx'),
        ),
    ]
