# Generated by GPT-5.2 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionevent",
            name="created_by",
        ),
        migrations.AddField(
            model_name="auctionevent",
            name="created_by_sub",
            field=models.CharField(db_index=True, default="", max_length=128),
            preserve_default=False,
        ),
        # Remove the old index before dropping the old field (SQLite table rebuild safety).
        migrations.RemoveIndex(
            model_name="auctionitem",
            name="auctions_au_owner_i_efb9d9_idx",
        ),
        migrations.RemoveField(
            model_name="auctionitem",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="auctionitem",
            name="sold_to",
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="owner_sub",
            field=models.CharField(db_index=True, default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="sold_to_sub",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name="auctionitem",
            index=models.Index(fields=["owner_sub"], name="auctions_au_owner_s_13b3c9_idx"),
        ),
    ]

