# Generated by Django 5.2.12 on 2026-04-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auctionitem',
            new_name='auctions_au_owner_s_351098_idx',
            old_name='auctions_au_owner_s_13b3c9_idx',
        ),
    ]
